### ISSUE TITLE
Ideation Note Check

### ISSUE THREAD

**Issue by F1nnC** [nighthawkcoders/portfolio_2025#358]
## Day One Grading

| Name Pair        | Idea 0 | Idea 1 | Idea 2 |
|------------------|--------|--------|--------|
| Aria & Cason     |     NPC   |    Sounds    |    Battle    |
| Aditiya & Aaryav |    Enemy    |    Obstacles    |    Game UI   |
| Aneesh & Veera   |    Levels    |    Scaling Diffuclty    |   Puzzle & Traps     |
| Akhil & Santhosh |    Projectiles    |     Levels   |    Power Ups    |
| Ethan & Logan    |     Gravity   |   Hazards     |    Weapon    |
| Matthew & Alex   |    Maze    |    Power Ups    |     Enemy   |

## Top 3 Ideas
> Not just the most popular but the scalable ones, that can be used generally
- NPC! (Nearby + press a key to interact)
- Obstacles (minus lives/just collision) this idea can be changed into power up as well
- User Interface (make a template with lives in score)

**Comment by jm1021** [comment]
Based off of feedback and my interpretations I will add the following to the game...

1. "NPC" class, my assumption is they could move on their own or be stationary.
2. "Obstacle" class, these will be stationary.
3. Collision engine, this would apply to Player, NPC, and Obstacles; or any future "GameObject" in the game.
4. The engine will provide method for GameObject to act on collision telling each "GameObject" criteria like  "this.top", "this.left"  and  similar properties on "other", like "other.who", "other.top", etc.

The addition of these items will impact JSON Object definition.
1. JSON Object will need to be tagged as "Player", "NPC", "Obstacle", "Background", etc.
2. Items like Player, NPC, Obstacle will need "Hit Boxes" to ensure collision is appropriately detected according to Sprite.  We need to determine if Hit Box is per frame of per Sprite.   My initial implementation will be per sprite.

**Comment by F1nnC** [comment]
## Day 2

| Name Pair        | Idea 0   | Idea 1  | Idea 2           | Idea 3              |
|------------------|----------|---------|------------------|---------------------|
| William & Yusef  | Monsters | Wepons  | Walls            | NPC interaction     |
| Avantika & Anika | Quests   | Jumping | Levels           | Day and Night       |
| Lara & Shay      | Story    | Quest   | Class Players    | Changing Characters |
| Lucas & Ethan    | Shooting | Ships   | Different Themes | Enemies             |
| Amal & Jeongyun  | NPC      | Weapon  | Shield           | Enemies             |

**Comment by jm1021** [comment]
Today, I liked some terms.  These are terms that help us figure out how to manage information and think about our game.

- class based
- 2D front
- 2D top

Actions, we need you to think about a simple but detailed quest in one level.  I believe Lara spoke about this several times today and it is really important.   Think about things we will provide from my previous post.
