### ISSUE TITLE
 P1. Brown, 3.8 Iteration Key Accomplishments

### ISSUE THREAD

**Issue by ShawnRay09** [nighthawkcoders/portfolio_2025#514]
# Overall...
From creating a lesson and researching about Iterations and loops, as well as listening and learning from other lessons, we learned...

-4 different types of loops and their uses
-Real-world applications of Iterations and Loops
-The importance of each lesson that ties into the fundamentals of coding
-How to fork a repository and work with others on a grouped repository
-Mastering the use of Jupyter Notebooks in order to share code effectively
-The use of pull requests and steps required to do one.
-How to divide work evenly and manage time
-To get creative with coding and styling and go outside of our comfort zone

From our research, teaching, and learning, we learned so much over these past couple of weeks. First, researching for loops, while-loops, and more allowed us to deepen our understanding of the subject and the self-taught aspect allowed us room for more questions, and therefore more answers. It helped us make sure our understanding of Iterations was solid and helped us know everything about the subject. Creating our lesson allowed us to run free with creativity, and even though at first it was a little rough with even Mr. Mort having to tell us to get more creative, in the end, we started to gain our senses back and started to go outside our comfort zone with styling. The interactive popcorn hacks with the quizzes and homework hacks allowed us to stay focused during lessons and kept the lessons fun and interactive. Though these hacks were simple, they simply just strengthened our base for these topics and were super important within the process of Sprint 2 in general. One hack we are super proud of is our "nested if statement hack" because though it is simple, the entire idea and application of nested if statements are interesting and the possibilities are endless. Understanding this, we added a challenging aspect in the form of a challenge hack where you had to combine for loops, nested if statements, try/except, and more. Overall, team teaching was a valuable experience that helped enhance our programming skills, and our results demonstrated our readiness for the next level or sprint.

| Submenu Button   | Highlights     |
|------------------|----------------|
| [Lesson](https://nighthawkcoders.github.io/portfolio_2025/csp/big-idea/3-8/p1) | Styling, glowing text, typing text animation, and GIF. Also, growing from comments and feedback. Ex. Bloooooooooob said to add more examples for loops in Python and javascript, so we did that. |
| [Popcorn Hack](https://nighthawkcoders.github.io/portfolio_2025/csp/big-idea/3-8/p1/3-8-1) | Implementing the challenge aspect of the hack for those who like to go above and beyond. It helped us see who deserves that 0.90+ grade.   |
| [Homework Hack](https://nighthawkcoders.github.io/portfolio_2025/csp/big-idea/3-8/p1/3-8-2) | Creating a hack that satisfied everything we taught in the lesson. We taught many things including nested ifs, iterations, and try/except, so we created one that requires you to use all of them.  |

| Name        | Issue                                                      |
|-------------|-------------------------------------------------------------|
| Shawn Ray   | [Issue](https://github.com/ShawnRay09/Iteration_3.8/issues/4) |
| Arya Savlani| [Issue](https://github.com/ShawnRay09/Iteration_3.8/issues/5) |
| Aarav Sonara| [Issue](https://github.com/Aarav445/Aarav_2025/issues/4) |

**Comment by Hypernova101** [comment]
GRADES FROM TABLE 6 PERIOD 1

 | **Assignment**          | **Weightage** | **Grade** | **Comments** |
|-------------------------|---------------|-----------|--------------|
| College Board Coverage  | 20            | 20       | Effectively teaches lesson, fully represents college board curriculum          |
| Python Examples         | 15            | 15       | Good Python Examples that were related to content|
| JavaScript Examples     | 15            | 15 | JavaScript matched Python in that both matched lesson content |
| Popcorn Hack Usage      | 10            | 15 |  Innovative ideas for popcorn hack |
| Homework                | 10            | 10 | Homework nicely represented lesson |
| Grading Plan            | 10            | 10 | Grading was thorough, everyone contributed|
| Original an Creative    | 10            | 10 |  Good creativity to add the typig animation |
| **Total**               | **90**        |    90       |      Great Lesson. Consider making it a _LITTLE_  more interactive in the future     |

**Comment by Bloooooooooob** [comment]
Scrum Master for Period 1 3.3 and 3.5
Grading for 3.8
**Relevancy Checklist**
College Board Coverage 18/20 -- Covers most of the content taught by the College Board
Python Examples 15/15 -- Used Python in your lesson but not enough Javascript
JavaScript Examples 11/15 -- Used Python in your lesson but not enough Javascript
Popcorn Hack Usage 10/10 -- 3 Popcorn Hacks posted
Homework 10/10 -- Nice homework hacks with challenge hacks included as well.
Grading Plan 9/10 -- The grading rubric is concise and reasonable
Original and Creative 10/10 -- Have nice font and title on the page, and also put image on the lesson which increase the memory point
TOTAL 83/90
