### ISSUE TITLE
P1 - 3.10 Team Key Accomplishments 

### ISSUE THREAD

**Issue by manahilkhann** [nighthawkcoders/portfolio_2025#524]
Our team did a great job problem-solving and working through different issues we had. We made sure to help one another when we faced a problem. For example, many of us kept getting an issue when trying to "make", so we worked together to figure out and fix the problem. We also helped each other understand the different topics we were teaching. After this Sprint we all collectively know much more about creating lists, appending elements, deleting elements, removing elements, finding the length of a list, and much more. 
-Manahil, Carson, Brandon, Jackson

 | **Team Member**          | **Issue** | 
|-------------------------|---------------|
| Manahil Khan | [Link](https://github.com/manahilkhann/manahil_khan_2025/issues/3) | 
| Carson Sutherland| [Link](https://github.com/carsonsuth17/carsons_2025/issues/4) | 
| Jackson Hensley | [Link](https://github.com/JacksonH24/jackson_2025/issues/3#issue-2590401380) | 
| Brandon Smurlo| [Link](https://github.com/BrandonSmurlo/BrandonSmurlo_website/issues/4) |

**Comment by Prad-coder** [comment]
0.8 - Reading off a script during presentation, showing that there wasn't mastery of lesson subtopics.

**Comment by ShawnRay09** [comment]
| **Assignment**          | **Weightage** | **Grade** | **Comments** |
|-------------------------|---------------|-----------|--------------|
| College Board Coverage  | 20            | 20       | Went over most if not all College Board Coverage in depth with multiple subpages          |
| Python Examples         | 15            | 15       | Great amount of Python Examples for every instance          |
| JavaScript Examples     | 15            | 15       | Great amount of JS Examples for every instance          |
| Popcorn Hack Usage      | 10            | 7       | Popcorn hacks could be a little harder and more in depth. Add challenges maybe          |
| Homework                | 10            | 7       | Again, could be a little more in depth and using everything taught in the lesson          |
| Grading Plan            | 10            | 10       | Liked how everyone had a role in grading homework and creating the presentation          |
| Original and Creative    | 10            | 10       | Love the pink color scheme, original.          |
| **Total**               | **90**        |     84      |       Great job team 3.10       |

**Comment by Prad-coder** [comment]
| **Assignment**          | **Weightage** | **Grade** | **Comments** |
|-------------------------|---------------|-----------|--------------|
| College Board Coverage  | 20            | 20       | Covered all the material required from College Board          |
| Python Examples         | 15            | 15       | Included multiple python examples related to lists.          |
| JavaScript Examples     | 15            | 15       | Included multiple java script examples related to lists.         |
| Popcorn Hack Usage      | 10            | 5       | Popcorn hacks could have been a little more challenging and in depth related to lesson content.          |
| Homework                | 10            | 5       | Homework hacks were way too quick and straightforward, should have been more in depth.          |
| Grading Plan            | 10            | 10       | Clear grading plan for the hacks.          |
| Original an Creative    | 10            | 10       | Good pink theme, showing creativity and individuality.         |
| **Total**               | **90**        |      80     |    Good job!          |
