### ISSUE TITLE
3.6 and 3.7 Key Accomplishments - Period 1 Brown

### ISSUE THREAD

**Issue by martijorbam** [nighthawkcoders/portfolio_2025#525]
# Key Accomplishments
- We taught how to use conditional statements: if/elif/else
- We taught how to use conditionals both with JavaScript and Python
- We taught how to use pseudocode
- We taught how to use nested conditionals, meaning that there are conditional statements inside another conditional statement
- We learned how to make a fork that we can all edit in order to work as a group
- We created several hacks in order to practice the content that we taught 
- We created solutions to the hacks to help them understand how the content we taught applies to actual useful Python or JavaScript programs.
- We created a quiz for both 3.6 and 3.7 

# Tangibles
### 3.6
https://nighthawkcoders.github.io/portfolio_2025/csp/big-idea/3-6/p1/lesson
### 3.7
https://nighthawkcoders.github.io/portfolio_2025/csp/big-idea/3-7/p1/lesson
### 3.6
https://nighthawkcoders.github.io/portfolio_2025/csp/big-idea/3-6/p1/hacks
### 3.7
https://nighthawkcoders.github.io/portfolio_2025/csp/big-idea/3-7/p1/hacks
### 3.6
https://nighthawkcoders.github.io/portfolio_2025/csp/big-idea/3-6/p1/solution
### 3.7
https://nighthawkcoders.github.io/portfolio_2025/csp/big-idea/3-7/p1/solution

# Individual Issues
Gavin Copley - [Link To Issue](https://www.github.com/GavinCopley/gavin_2025/issues/7)
Marti Jorba - [Link To Issue](https://github.com/martijorbam/marti_2025/issues/6)
Gyutae Kim - [Link To Issue](https://github.com/GyutaeKim1/Gyutae_2025/issues/4)

**Comment by Bloooooooooob** [comment]
Scrum Master for Period 1 3.3 and 3.5
Grading for 3.6 and 3.7
**Relevancy Checklist**
College Board Coverage 16/20 -- Generally good coverage of college board content but there were a few things that could have been developed a little bit further.
Python Examples 15/15 -- Nice mix of python and javascript in your lesson.
JavaScript Examples 15/15 -- Nice mix of python and javascript in your lesson.
Popcorn Hack Usage 0/10 -- No popcorn hacks present
Homework 10/10 -- Nice homework hacks with challenge hacks included as well.
Grading Plan 8/10 -- Pretty simplistic grading plan. Not much on it.
Original and Creative 9/10 -- Background color gradient and quiz is a nice touch.
TOTAL 73/90

**Comment by Hypernova101** [comment]
| **Assignment**          | **Weightage** | **Grade** | **Comments** |
|-------------------------|---------------|-----------|--------------|
| College Board Coverage  | 20            | 20       | Good examples that represent CB          |
| Python Examples         | 15            | 20       | Hacks effectively communicate Python usage           |
| JavaScript Examples     | 15            | 15 | Hacks effectively communicate Python usage |
| Popcorn Hack Usage      | 10            | 10 |  Interactive popcorn hacks |
| Homework                | 10            | 10       | Challenging, but not too easy homework          |
| Grading Plan            | 10            | 5       | Try make the lesson longer the first time to prevent repeat lessons          |
| Original an Creative    | 10            | 5       | Try make the lesson longer the first time to prevent repeat lessons |
| **Total**               | **90**        |     **80**      |     Try make the lesson longer the first time to prevent repeat lessons         |
