### ISSUE TITLE
CSSE

### ISSUE THREAD

**Issue by F1nnC** [nighthawkcoders/portfolio_2025#530]
| Group | Lesson | Day |
|-------|--------|-----|
|  Ethan, Cason, Aria     |   Variables     | Wed 30th |
|  Aneesh, Aaryav, Aditya   |  Math expressions  |  Thu 31st  |
|  Shay, Yusef, William   |   Conditions  |  Fri 1st, simplify homework |
|  Anika, Lara, Avantika  |   Nested Conditions  | Mon 4th, add parts |
|  Lucas, Ethan, Alex    |   Classes and Methods  | Tue 2nd, change homework for class, simplify |

| Group | Lesson | Status |
|-------|--------|-----|
|  Santhosh, Akhil, Veera | Data Abstractions | Fri 8th |
|  Kian, Srinaga. Michael    |   Iteration  | Tue 12th |
|  Logan, Matthew, Hamin   |   Strings  | Wed 13th |
|  Jeong, Amal, Nora   |   Booleans  | Delayed, no pull request|
|  Dylan, Leila, Zoey     |   Arrays/Lists  | Delayed, no pull request |

## Three Seperate Notebooks
> One for each person

*  If you teach on same day as another group HW will be 20 minutes, otherwise plan for 30 min.
- Lessons will be taught in teams of 3s, you should organize your teams today.  Each person will teach 3 and have popcorn hack for 2 minutes (5 minutes total).
- You will change lessons that were provided and try to pattern new lesson after our gaming code.   You can use your personal adaptations.  Be sure to add JavaScript Objects and JavaScript Arrays to every lesson as applicable.
- Lesson will have Popcorn Hacks, things that you do right after each Student Teachers and HW.  All lessons will have Jupyter Notebooks and use HTML DOM for outputs, console.log will be supplemental.
- You will prepare lessons, assign lessons, grade homework.   Popcorn Hacks and HW should be weighted  (ie 40%, 60%).     Homework should be about 1/2 hour.
Finn will help coordinate signup list and other logistics, like pull requests.  
- We will start Tuesday with Student Led Teaching.  Lessons can be taught in any order.  Lessons will be about 15 minutes, each person teaches 5 minutes including Popcorn Hack.  Lessons will be taught every day with 1/2 hour of homework assigned for second half of class.  Assignments are due 9pm on day of assignment.  Be sure to have Utterance setup to receive HW.
- This is a Critical Assignment to meet class requirements and college articulation.  It is also a great restart for some that feel a bit begin.  Everyone needs to capture Homework into their personal blog.
- If you add Game Ideas to your Homework it will make students very happy to be able to progress their game!!!  Be creative, don't use lessons exactly as they are in the link.
- Be sure you review your team members work before  each Pull Request and Teaching.   All lessons should have at least one Pull Request by Monday 6PM.  Remember lessons need to be done, or close to final on Monday so you can focus on Homework thereafter.

**Comment by jm1021** [comment]
Resources for lessons.  All of these lessons have Python and JavaScript.  Just do JavaScript
-[CSP 1]( https://nighthawkcoders.github.io/portfolio_2025/csp/big-idea/p1/fundamentals)
-[CSP 2](https://nighthawkcoders.github.io/portfolio_2025/csp/big-idea/p2/fundamentals)
-[CSP 3](https://nighthawkcoders.github.io/portfolio_2025/csp/big-idea/p3/fundamentals)
-[CSP 4](https://nighthawkcoders.github.io/portfolio_2025/csp/big-idea/p4/fundamentals)
-[CSP 5](https://nighthawkcoders.github.io/portfolio_2025/csp/big-idea/p5/fundamentals)

For classes lesson.  These lessons are in Java, but same topics can be adapted to game code we are doing in JavaScript.  
-[CSA 1](https://nighthawkcoders.github.io/portfolio_2025/csa/period1/unit5/intro)
-[CSA 2](https://nighthawkcoders.github.io/portfolio_2025/csa/unit5/)
