### ISSUE TITLE
Sprint

### ISSUE THREAD

**Issue by tarasehdave** [nighthawkcoders/portfolio_2025#82]

**Comment by LiliWuu** [comment]
| Skill                                 | Mastered (Y/N) | Rank (1-4) | Ratio | Notes                                                       |
|---------------------------------------|----------------|------------|-------|-------------------------------------------------------------|
| Laptop Verification or Cloud Workspace| [ ]            | 0          | 0.0   | Verification by Linux commands notebook                     |
| VSCode                                | [ ]            | 0          | 0.0   | Live change code, commit, make, run localhost, test, debug   |
| Show VSCode GitLens                   | [ ]            | 0          | 0.0   | Verify commits, show change, comments, reset to commit, run on old commit |
| GitHub student_2025 repo              | [ ]            | 0          | 0.0   | Template create, push changes, verify ID, review analytics   |
| GitHub Pages Actions                  | [ ]            | 0          | 0.0   | Review runs and verify runtime, receive demo                 |
| Hacks Tools & Equipment Play          | [ ]            | 0          | 0.0   | Hacks                                                       |
| Hacks GitHub Pages Playground         | [ ]            | 0          | 0.0   | Hacks                                                       |
| Hacks SASS Basics                     | [ ]            | 0          | 0.0   | Hacks                                                       |
| Hacks Frontend                        | [ ]            | 0          | 0.0   | Hacks                                                       |
| Pair Programming                      | [ ]            | 0          | 0.0   | Tangibles that show coop work                                |
| Total            |                |            | 0.0   |       |
| Average          |                |            | 0.0   |       |



| Skill            | Mastered (Y/N) | Rank (1-4) | Ratio | Notes |
|------------------|----------------|------------|-------|-------|
| Attendance       | [ ]            | 0          | 0.0   |       |
| Work Habits      | [ ]            | 0          | 0.0   |       |
| Behavior         | [ ]            | 0          | 0.0   |       |
| Timeliness       | [ ]            | 0          | 0.0   |       |
| Tech Sense       | [ ]            | 0          | 0.0   |       |
| Tech Talk        | [ ]            | 0          | 0.0   |       |
| Tech Growth      | [ ]            | 0          | 0.0   |       |
| Advocacy         | [ ]            | 0          | 0.0   |       |
| Comm & Collab    | [ ]            | 0          | 0.0   |       |
| Integrity        | [ ]            | 0          | 0.0   |       |
| Organized        | [ ]            | 0          | 0.0   |       |
| Total            |                |            | 0.0   |       |
| Average          |                |            | 0.0   |       |
